name: Contribute an Icon ➕
description: Contribute a new icon to the library.
labels: [Icon Request, Contribution]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for submitting new icon *contributions* only!

        ---

        **_Please note_: [We are no longer accepting new brand icons into MDI.][1]**

        We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

        ---

        [1]: http://dev.materialdesignicons.com/roadmap/brand-icons
        [2]: https://simpleicons.org/
        [3]: https://github.com/simple-icons/simple-icons/issues
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: "Before submitting a new icon request, please confirm the following:"
      options:
        - label: I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
          required: true
        - label: I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
          required: true
        - label: I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.
          required: true
  - type: textarea
    id: preview
    attributes:
      label: Preview
      description: Generate a preview of your icon using our [preview generator](http://dev.materialdesignicons.com/contribute/github). Your icon *must* be combined down to a single path to generate a preview.
      placeholder: Paste the generated preview of your icon here.
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Icon Source
      description: ZIP the SVG source files for your icon(s) and upload it here. Your SVGs should only contain the single path used to generate your preview.
      placeholder: Upload your ZIP file here.
    validations:
      required: true