name: Ask a Question ❓
description: Unlike other repos, we're fine with questions.
labels: [Question]
body:
  - type: markdown
    attributes:
      value: |
        *Note:* Please make sure it is relevant to the icon pack and not too specific to a Framework/Library.
  - type: textarea
    id: question
    attributes:
      label: What is your question?
    validations:
      required: true