name: Request Documentation or Guide 📃
description: Request a new how-to guide or documentation for a specific framework.
labels: [Documentation]
body:
  - type: markdown
    attributes:
      value: |
        *Note:* Please make sure your request is relevant to the icon pack and is not already covered in existing documentation.
  - type: textarea
    id: question
    attributes:
      label: What new documentation or how-to guide would you like to see?
    validations:
      required: true